.PHONY: build clean

build:
	@javac -encoding ISO-8859-1 ./MainFrame.java
	@javac -encoding ISO-8859-1 ./Chopstick.java
	@javac -encoding ISO-8859-1 ./ChopstickArray.java
	@javac -encoding ISO-8859-1 ./Philosopher.java
	@java MainFrame
